apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    targetRevision: main
    path: storage/rook-ceph/storage
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
