apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-tools
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    targetRevision: talos
    path: tools/rook-ceph
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
