apiVersion: v2
appVersion: master
dependencies:
- name: common
  repository: file://../common
  version: 0.1.20
description: A Helm chart for gen3 Dicom Server
name: orthanc
type: application
version: 0.1.4
