apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: small-llm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    targetRevision: talos
    path: llm/small-llm
    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: small-llm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
