---
- name: Join secondary control planes
  hosts: control_secondary
  become: true

  vars:
    primary: "{{ groups['control_primary'][0] }}"

  tasks:
    - name: Wait for API server
      uri:
        url: https://{{ hostvars[groups['haproxy'][0]]['private_ip'] }}:6443/healthz
        validate_certs: false
      register: result
      until: result.status == 200
      retries: 30
      delay: 5

    - name: Fetch control-plane join script
      slurp:
        src: /etc/kubernetes/bootstrap/control-plane-join.sh
      delegate_to: "{{ primary }}"
      register: join_file

    - name: Join cluster
      shell: "{{ join_file.content | b64decode }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
