apiVersion: v1
kind: Node
metadata:
  name: cpu-worker1
  labels:
    worker-type: cpu
---
apiVersion: v1
kind: Node
metadata:
  name: cpu-worker2
  labels:
    worker-type: cpu
---
apiVersion: v1
kind: Node
metadata:
  name: gpu-worker1
  labels:
    worker-type: gpu
---
apiVersion: v1
kind: Node
metadata:
  name: gpu-worker2
  labels:
    worker-type: gpu
