version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: 68o2pt.tr6tfh2hmxrtllx4
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBOXlmVHpHT0h5TWo0V3R3dzBzbTdrVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdPRE14TURNMU9URXlXaGNOTXpZd09ESTRNRE0xT1RFeVdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUwyemplTi9FQWlrakZnTDZRbGJkQ01kOGQyeG9BN3pqdDhCCnJQcGxyTXc1bzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJpR2hrWEZFTGR0cUd1QQptWTVLRTUwamludjhNQVVHQXl0bGNBTkJBQWNmMlYzaWRxSjZnOWxjWG5hUW80aGdaM3E2ZnlZUkxjRXVhSjNaClMyczlYekN4bVdubzEvUk8ycGJVaUh2MUttY3dQVkN5NVVTWjIwNy9XNzNrTGdFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJSzIreGhCdHpKdjI5aFFpRERKT3c0YVlwNkszaFpXanRYZ283ZlBYMmE3aQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.36.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    install:
        disk: /dev/xvda
        image: ghcr.io/siderolabs/installer:v1.13.7
        wipe: false
        grubUseUKICmdline: true
    time:
        servers:
            - 169.254.169.123
    sysctls:
        vm.max_map_count: "262144"
    features:
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: tYlO8v-y164KOdkPeC1x0mZkRJNmK6D0FQQJFS6u7h4=
    secret: 3/PUMdX6aoF/FTYFHA9gyu9Dl+dDovOqnfgMgmI5SZ4=
    controlPlane:
        endpoint: https://100.61.11.217:6443
    clusterName: ceph-cluster
    network:
        cni:
            name: flannel
            flannel:
                kubeNetworkPoliciesEnabled: true
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: ghccvy.gt9odi7vpp2p6q9h
    secretboxEncryptionSecret: DIlfBJPimi/edgfFSYJ9np7XfXRK9MWzEtDGIKki/Qo=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVMrZ0F3SUJBZ0lRTlgvQWVIY2lLbFBTUzd0emNWa3k1VEFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNRGd6TVRBek5Ua3hNbG9YRFRNMk1EZ3lPREF6TlRreApNbG93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCREt5dHJQZklLSEQ0K2krWFB1a2xHZVk2S29WUVVKOTJzanE4Ri9YaXdla1pUOGdqc0F2MnNiL3NYWDgKSHRzKzhSbHp0KzRISHRPZkZSZnBNdDFjVlplallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVueWdxMEp5MlplVlBRaDYxRWwraUE0ZzA5NUl3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUlvTEJ0YlAKN3duTzVNMVkxT2ZJRjY1N0N4dmdoMjc3UFJBU1hTbUV0KzFsQWlFQTEyUTN1bzFtam1OZ0lSZTZXc3VhVUxFbwpUSXhRQXhIdmtNT2JMWDkydDMwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUphRW9MVGlBek9QZ2ZsN200QVlMcGtkZStlOEk5RVphRzVySTA5WnlyYUZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTXJLMnM5OGdvY1BqNkw1Yys2U1VaNWpvcWhWQlFuM2F5T3J3WDllTEI2UmxQeUNPd0MvYQp4dit4ZGZ3ZTJ6N3hHWE8zN2djZTA1OFZGK2t5M1Z4Vmx3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZVENDQVFhZ0F3SUJBZ0lSQUpXam1FeU9YSGlWdlNkZFBnWStlUkl3Q2dZSUtvWkl6ajBFQXdJd0FEQWUKRncweU5qQTRNekV3TXpVNU1USmFGdzB6TmpBNE1qZ3dNelU1TVRKYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVM3dGJPQVNicWlSL1ZuSGFUcW5qeXJlSnd3c2pvdTFZVkMxMklQWExkcjBKS0djYnk2CjEzdWhyMHJYQVBnVnVHOG5kUndyeDluUmpPU1ZidGI4VmIvd28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXcKSFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGTWpXRHJFMWJJNVpNZkFUMkxDZURDUGdPN2NyTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDCklRRHNwQnRLYTdORWJsbnBzcm9CRlZsOExTVTRodnczRGtDcW5WSm9KTVZmT3dJaEFORGRBdm0vVUJVSmhxM04KemR3YUwzVjlsMUNqM0hnZWkzeEJ6dGtkU3hxcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUlkNlo1R1cyRWNDelNHV0J1NXVlRGRRZ3h0TG9zR0NST2VvM3BLdU1qUlNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdTdXemdFbTZva2YxWngyazZwNDhxM2ljTUxJNkx0V0ZRdGRpRDF5M2E5Q1Nobkc4dXRkNwpvYTlLMXdENEZiaHZKM1VjSzhmWjBZemtsVzdXL0ZXLzhBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBNWVBNUxXZXJaS1ozc0dnVzVlZ25VUXA4eTFCSHhML0hPWDlBZUUrSG05ZnMvZlo2CldFcUlMUzFvWGR0a1N4bVRLOFQ1VEl6WExGVVVxVmxKUlZyMkFmem1WMm5vUklORzRzMGw5Tm1MVHplclBwYmEKYkdXclY5TWpPRHYrTlV2eU04djI1NlA5U2MrOTJGbkpwN05ieEFzTWNiWlIzQjEyenU2a2t5eFJvdU1wK2xrUQpuanplT29zbHZmeHZHTXBmTzV1QnN3bUlETGpYLzdYRmRxbUlkWDNod2VZZ255cXo3WEtVSE0yUElQYStLaU4yClhmM0VrTVlCR2pEbTltVjR3cXlvQU5HT3lFUjhpZTE3cEFoTnJJVlBHbVdPRkJva0dxQmZJdytEZDRWUlJLNHgKVWRUS3FJSHVHbE9tTjZPUEtBTm5IclNiNFFQL281U1lsQzZ2VUxVYTA5ZUI3TEd5MHAzMHR1VzJQbVhrSG5IdgptdXprUGVEcTZ4MHYyYkk2cVRtSDRrdjVkR1FXMmZQQUFPM014UHJFUWU4UjlBSWNydWF0N1YvZ0JUZlh1QVlKClNUVUc3dXViejl3SGtPbEFnWlUxRzdRWVE0a2hhY1hYMkJENmlJaGxxU1NGdS9JR21tUkF4RVdoZjU1UG1xK0kKUlgvSmtnbnZaT25QZ2MxOXR1dDJ5WmlYNTBWR1JldG1RQy9oSXNvNk4ya3Ywc2c0dkd0V1dSdmRGYWVLR1NpKwpldmo4bFdjZmxpayt2bDIrSExORU5vWlh6Y2tadktVUU81R1NZUWJQcFN5WnB4aVJ2TjhVNS9lRjkrVWRvbi9wCkR1RG8yVzZwazRPUVhrbThqeGtkb21lVmhUZkNUMnlGcWw1c2l3Z2xmd0REQktUb0JYNVlET2YwaGdNQ0F3RUEKQVFLQ0FnQVEzeFlUT1FxaFJuNStXZ1ZrTmxlOFlQS3IwV2FURUNoRkZndmJTS3NCU3lXL3RmbGd4WWVkR1RvUgp1V3B4QUoyR2x0eGRPL0VHOWUrZ1JrZFVhY3FvZHJGSk5TS3c5Sm1kUjhWRFpUd09RbDIxS0VrN3IzS1Y3WThtCkwzRUc1RjRRWXlYcDltVStwNXFkYUdtZWYxRjYzL3kzMDlQS1BmZGNWTE9MZ2JNMEswd0hiY1lFZHg4d1dNb2EKV1k2bDJTU0lNVytoZmsrWDczRWErWEpXdFRhb3VPWjYzck1DTzVZZEZVMjlsM0NyMExCQVUzMzZoQWVMUUowUQpHUXE2aHRRSUpiZm01M3A5UkZtSG5nQjNGNHpyM3BUaHNSWnViMFM3RjQ0aitwMkJoaTFpeHc0am5XU0tYWTdtCks4R0ZUK0hQNUFBTGh1SHg3K014VkZTbWU0NnVVQlgvelJFWklENS9JbnlkQkpIbHdGOEdBeGpQaXJuZTUyNkkKKzdVa1o5SzdreTNNVzZYRVFmd2NpRVloc1p2QXU0YmpybWVKbTdPaDBHTE01WHpEU1BXbzRJektBQUNHalVtYQpZbkdxdjRGbmoyellDbzM2dUxxNVdNeDFzZ2l5QUNpd3IydEt4emRwd1Jic3pUQUNFcHBGc0JvaE5EVGllZkVtCkhBYktsekZzVk8yVWJuREhMQ1MvMnlJVnJwU1ovUWdhMlBrZ255aHdQcHcvMkJ4T1N1dXQ0dUpZL2d6Q1gxVksKNXorY3dKNXl5MUgxMGh5WHlDSG1HZDVoNVBCK29XcTlTa1hudTcwOHVSWHhya2VyVW92MFQyT3QrekJmY1RLdgplanZzdzVyOHI3cGhlUGtLQ243WkFDYWJvMlN1bzhmVzJWYThlbkM2Nzc4K3VNd2Y4UUtDQVFFQS9vZStJazh4CkNuaUdRdFExSjR3Vnl1TDNjMkwrdm45dm05MWJlR2Z6SnZrc3NueE15OFo3SFdxbi9Cb0tQNDZ6T3BVTlNKOUsKWDJrNXEvZUd5b2FXQjYzQm82UW1IdSt3bVFSOThtd21tc29TMG14WEN2ZDRKME1RMElBYW5hUW5oTGlYbUxMTgpmZDFtZ1lzRlhYd2tBMkJWRHlpK1djYStjWkI1VkVuYVdZSzQ3WlZ6UUNNWVFydnVLMWFSeTRTL1MzMS9ObDUyCk85R3Nsc0NvMFJBTk1CdGEzWGJwWExKdzcrNklnMnllMStydEd3UEsxMWlTVmE3aUxWUzNBQjd5RmZ4VFpLYUEKY1NXdEpVUE1RbXg0MVJYcW1SOHM5ZUJRdFJCREV1dllSbC9NWWxEM3VPRSt1cFVkN2psNS8xVU1DV2pkY1R5OApzcDFJTmhMVVZHdk41d0tDQVFFQTV6UUpGeStpeDdhb3NxTmFuVlM0TDNReTZPV3JvL0N4ckZXYUt6YlBaT0FECjB0NE0ydUl2NVVHQ2hwR0hJK1MrY1ZRdkp4TXVUbS9rSk52TkV4UTBPNERVaGhKbWJINy9iSEx1Nm8vMlUxbloKUktBaWVIdFBwOVVWTGFtUjQyY3lCdFVuUVZCUUpLTHNpbTVUdGZlZ09zdnFzOXkrZTJBSk13NGdOalM1SDZ6agpDdDhIazBHRjFVNHprTEpKSUtXWHJDOG5lNFZocElKWDhibHVFSFlMenJnS2VvZFYrdTZ2RFV2NHBqZ1k2UzQ2ClFHVDZHbUM5enFoZHVnV2R1YXFZUHYxVDJ5Y1loQWZmUnJiaHlocVUrcEVYMStNSmVDa1NtQS9ibnZwZkZFemkKZ01adDFKSkQ5WVMzeGcvenplSkZtTHkwTzNTRHRMUFZhMzUyb2FWcmhRS0NBUUEwOG9YaDJ6bG5aVFVBdCtZcQp5T0JMcVRVeWdwaGRobUx3T0hicnNDd0xvbS9pM1NxWWhUeGRIUysrcUtnVEdwczhCMytRNk5udXlSUGZLd21XCkhiTWQrODQ1UFU5VXhpV2xYeUxZQ0JscnY3ZDBvR2JtK0IyOWhSejlVbmkyN0V2d052b0tJTC9RZS9yejNiaUsKL3VUNjh0SWU2aW5Xd1JvaXc1d0pwYWRQVVhzb3FSc2xiMmQva2xwMEYza1NyaFdoSFlVV0NVWnRJU3ZXM0ZNQgowbVg3Nk9UWkJ3QjZjUUEvV1E1NjBHQ21wODhVL0kvNGhndEMyYk5oSEt0STBpY24zYXAzV0krRmVnSHZxNC9WCkRYMkJUaUxVSVlFWDBNYlpNMzNRZE5FenFuLzR2OEVZYTNyQ0UzejdibWRyYndTbS9ISjhPTmRFREtYVjRjcmIKbU9WbkFvSUJBUUM5MG1Rd1RDVDZrWVpaL0hKV1FBdGtzcU5sd2NNMU8xVzBweWVIbVYyWGRiRE4vUTlTMm1mMgpjdDJtZkc4VzBpUmx5WGRaUG85RFNPeG9NcXBob3JIcnRLOUlVRzBWWVFOMjE3bytqT254cnhBS0h1dU9QYmU5CmxOM3BlcEpUd1JNNnR1Q2U2RUNVZzh0dk1IdThKODIrMkZNZlR2cDVNdlQ2blB0blpjd2tMSDdRR3lNT0RMckQKMFl2V25mb2FPcnFYWExPdTMyaTJkMm1iQmVKTzA0eUlNV1F4QzFKVlRvZ2NnNlpuV2lGaHVWbU1LeHVJY3FzRAp0QW9YdzZxbW1HQ2RQc0lOYVVEZ2pkSU1MZlNkU1V2Tm1UaVpRRWN6QjQzRG1TbDRraGxrQW1mbzBJRzJDRXlSCmxHQ0oxZWtXdlZMa3Z2Rys2citEcWk1c0xnMWFWQVU5QW9JQkFRRHNjOWhSK1JEWDE4NllNSXorbGZyZTY5MnIKUGRXdm84aUQ4N0hRckpzVUE0TDlQVjRFOWdHS3JKS2FSZGRrMWJmU0VhU3JsUEJlZk10NXZwaGppUHFMaFh1KwpBM1lLVE1jZ1Yzc0FDMHIyUHRwL1QxR3pxTDMxZE90RlpqaHhXQVN0WFNPd1VaVXhiWGpiN1ZWSUg5TENMSDc1ClpXS2lrMzhseTdvYjhsUlRxRnYyR1lXdkZmMUU1bjE2QlRKSXBJVWdPQWwwNG0xUFN2K1VzUVkyQ0Q3d2FqUzMKZjFPbzFvbERXREdwbVloYUdXb1ptZmkzelNuWDA1MTZWOFQ1aVB2TXNhUjdodU9GTHRHSURFVDcwWWhYUmxjaAo5SnR3WFE4MVl3emJpZzRkaDc5dzVKZnNHSjRuSnZTODVSSVFHVm5vL29KbUF3K0tycnZDY2ZHdFZJRlEKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.36.2
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.36.2
    proxy:
        image: registry.k8s.io/kube-proxy:v1.36.2
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.36.2
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmekNDQVNTZ0F3SUJBZ0lSQUtVNFFEU1BTNUY3aTdxQjFkUlU3blF3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TmpBNE16RXdNelU1TVRKYUZ3MHpOakE0TWpnd016VTVNVEphTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRZitYMlR2TmhzCjB3bjRaSTRMNHR5cTRCZzViTzljQmgvMjNKYkZhZjM3QWhZb0dkcTRtaXJZdWp4UGxoU0dWYVVIMjRxUW9RNXUKUWJnU2FOeGRvclhCbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk92Q1c5L1k4NjNtCnM0eU84cHhpUmFidE92azFNQW9HQ0NxR1NNNDlCQU1DQTBrQU1FWUNJUUNhSUo2bWFYdlJBNFlrYk8zYXc1U3QKMm1DaVptVzA5eUlqV0ZuMzVLcTRzUUloQU5kZG92VGxiUWZTdUFPcEJaV2h0akxEMGVPUlduVjJ1QmN0ejNxbQpZS3NVCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtHVytvQVFpZzlycG9iM1RIazdEWHlmbnhEa3ViQTRSRTViMTBKNThveHJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSC9sOWs3elliTk1KK0dTT0MrTGNxdUFZT1d6dlhBWWY5dHlXeFduOSt3SVdLQm5hdUpvcQoyTG84VDVZVWhsV2xCOXVLa0tFT2JrRzRFbWpjWGFLMXdRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
