---
- name: Label Kubernetes worker nodes
  hosts: control1
  become: yes
  tasks:
    - name: Label CPU worker nodes
      command: kubectl label node {{ item }} worker-type=cpu --overwrite
      loop:
        - cpu-worker1
        - cpu-worker2

    - name: Label GPU worker nodes
      command: kubectl label node {{ item }} worker-type=gpu --overwrite
      loop:
        - gpu-worker1
        - gpu-worker2
