---
- name: Install Kueue using Helm
  hosts: control1
  become: yes

  collections:
    - kubernetes.core

  tasks:
    - name: Install Kueue Helm chart
      kubernetes.core.helm:
        name: kueue
        chart_ref: oci://registry.k8s.io/kueue/charts/kueue
        chart_version: 0.18.1
        release_namespace: kueue-system
        create_namespace: true
        wait: true
        wait_timeout: 300s
        state: present
