---
- name: Label control plane nodes
  hosts: control_primary
  become: false

  tasks:
    - name: Apply control-plane label to control nodes
      command: kubectl label node {{ item }} control-plane=true --overwrite
      loop: "{{ groups['control'] }}"
      tags:
        - set_labels
        - labels

    - name: Get all nodes with labels
      command: kubectl get nodes --show-labels
      register: nodes_labels
      changed_when: false
      tags:
        - debug
        - labels

    - name: Display node labels
      debug:
        msg: "{{ nodes_labels.stdout_lines }}"
      tags:
        - debug
        - labels
