---
- name: Verify cluster
  hosts: control_primary
  become: true

  tasks:
    - name: Check nodes
      command: kubectl get nodes
      register: nodes
      changed_when: false

    - name: Show nodes
      debug:
        var: nodes.stdout_lines
