apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    path: charts/fluent-bit
    targetRevision: main
    helm:
      valueFiles:
        - fluent-bit-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: fluentbit

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
