apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-trainer
  namespace: argocd

spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    path: charts/kubeflow-trainer
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
