apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-storage
  namespace: argocd
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    targetRevision: main
    path: storage/rook-ceph

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
