apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlproject-pvc
  namespace: mlproject
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: scratch-sc
  volumeMode: Filesystem
