apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    targetRevision: main
    path: charts/opensearch
    helm:
      releaseName: opensearch
      valueFiles:
        - opensearch-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
