apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    path: postgres
    targetRevision: main
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: gen3-db

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
