controller:
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: dedicated
      operator: Equal
      value: ingress
      effect: NoSchedule
  service:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
