apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    targetRevision: main
    path: charts/eck-stack
    helm:
      releaseName: eck-stack
      valueFiles:
        - elasticsearch-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
