---
- name: Set rook-ceph-block as default StorageClass
  hosts: control_primary
  gather_facts: false

  tasks:
    - name: Mark StorageClass as default
      tags:
        - storageclass
        - rook-ceph
        - default-storageclass
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: rook-ceph-block
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
