- name: Deploy storage class
  hosts: control_primary
  become: true

  vars:
    local_file: "{{ playbook_dir }}/manifest/scratch-sc.yaml"
    remote_file: /tmp/scratch-sc.yaml

  tasks:
    - name: Copy storage class YAML to control plane
      copy:
        src: "{{ local_file }}"
        dest: "{{ remote_file }}"
        mode: "0644"

    - name: Apply file system

      command: kubectl apply -f {{ remote_file }}

    - name: Verify pods
      command: kubectl get storageclass -n ceph-rook
      register: pods

    - debug:
        var: pods.stdout
