apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    targetRevision: talos
    path: charts/keycloak
    helm:
      releaseName: keycloak
      valueFiles:
        - keycloak-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
