type: postgresql
mode: standalone

version:
  postgresql: "16"

cluster:
  instances: 1
  storage:
    size: 8Gi
    storageClass: cnpg-sc

  enableSuperuserAccess: true

roles:
  - name: keycloak
    ensure: present
    login: true
    superuser: false

databases:
  - name: keycloak
    ensure: present
    owner: keycloak

backups:
  enabled: false
