apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-6"

spec:
  project: infrastructure

  source:
    repoURL: https://github.com/josephjohnjj/kubernetes-training.git
    targetRevision: talos
    path: charts/argo-workflows
    helm:
      releaseName: argo-workflows
      valueFiles:
        - argo-workflow-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
