version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: cddldi.6i0ylop23gh2t4y6
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBck5qRTFySkptamxubTVRU1ZidGZ0VEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdPRE14TURNd01qRXlXaGNOTXpZd09ESTRNRE13TWpFeVdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQU42SXBJTDd3UkdHTjJHcG5tRUNzSXQ4NWhyTG52RytSaUhRCkF3YW8wRDdsbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRklCSEZIcUU3VVhRdzB3RwpMYmYya29Fc0oyWGdNQVVHQXl0bGNBTkJBRTh6UzU3SzBMNUtJdm1CTWtaZmFETFdjbC9DSngwdHgzcW9aMDRBCldnbXFxRGJWSHZOdW9EUUlqVjA1NnNOc1J5RmZQQ0dmei9ZWWh5YTRjUEhLT2dzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJR2pSZnArRGhjRHhUcmtJRjIwV2htem1EczdkWUtFTjF3eE14WEJ6Y042LwotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.36.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    install:
        disk: /dev/xvda
        image: ghcr.io/siderolabs/installer:v1.13.7
        wipe: false
        grubUseUKICmdline: true
    time:
        servers:
            - 169.254.169.123
    sysctls:
        vm.max_map_count: "262144"
    features:
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: pPkmDG4Qd9L07WNURv1TXGb5qSXx54NTwlY1QZ9Slwo=
    secret: sKqlgrUgr99/oVHdblm+2iloBZNL4u4t+spV0CNZp40=
    controlPlane:
        endpoint: https://100.61.11.217:6443
    clusterName: gen3
    network:
        cni:
            name: flannel
            flannel:
                kubeNetworkPoliciesEnabled: true
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: cixs9k.hc7sxseamo6mcxuu
    secretboxEncryptionSecret: j3OizgR/LTo7p7B06Eh/5nlhJhNYeqAfVp01LUgdMbc=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUtqYThPU0FlSGRDT3pLeEZlMStleUF3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakE0TXpFd016QXlNVEphRncwek5qQTRNamd3TXpBeQpNVEphTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRwM1pXNHhvbHVBUkpMNGNUNHlVVGxxU3VSeVFybW54REVjcS9SRTBsb1huYlJYM0dBaURtK01kb2IKakNMWG1abU9RQ3BzQjdxMmNNYjZnZUo0bTVoVW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGSEFJb0Y4WUlTaGpNcTB1OFRXMXJDbC9SMzNBTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDWlRzOW4KU0JlUStjL3pWS0QyeTRrTm50dFhpR1JxdDRoMXk3dk42MHo5cXdJZ1ROM2VxNjBSVDFRcy8wc285Z1AwckFVWgpnSFMxS3d4Z085amUyb2FMUjRjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1mQW9pcGxJeFVyT0xqalJQVWU1ZUFqeFZ0K3VsOWtiYURkUlpKdHRXbldvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNmQyVnVNYUpiZ0VTUytIRStNbEU1YWtya2NrSzVwOFF4SEt2MFJOSmFGNTIwVjl4Z0lnNQp2akhhRzR3aTE1bVpqa0FxYkFlNnRuREcrb0hpZUp1WVZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYakNDQVFXZ0F3SUJBZ0lRWEVyclRod3hqMWx6U3RCTXhPZWMwakFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMk1EZ3pNVEF6TURJeE1sb1hEVE0yTURneU9EQXpNREl4TWxvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCSkdOZzErbC9BNTJ2ZWJobUJvNDRhTkM5aWp5dGtzb1pWZU1BM3hoczV3MlcveklyRnY4CnlUYytXb1VOdkxRTm9qemI2c0RZaVFwc2tIaXJwUllPNGZxallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVV4V0VORVFKY29BbjFEZ1VYVjJicWViSkNOL2d3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnCkYzQTdGWmhCNzlhVThlY3piOWpWajRqMXVvWjlVTzBWa2h3bnY0eEQ2MzBDSUVReVBmRkhOa3FBWkRNV0pLVzUKMzBvSmJYbi8rWVRkVisxbUhtUUdPWFk3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhWb3g4eE91T0ptdDdMZ21FZFFNY044bWRSVnREamFYZGRtb0tjMGJWYjJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFa1kyRFg2WDhEbmE5NXVHWUdqamhvMEwyS1BLMlN5aGxWNHdEZkdHem5EWmIvTWlzVy96SgpOejVhaFEyOHRBMmlQTnZxd05pSkNteVFlS3VsRmc3aCtnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBcGlxc0dvcWZ3Z3pPSVRjZmRVaHMxb1BRSHpLTzRmRnJpUzl4RlMyVFczTytCQWd2CkZLUkpyeE9FSThrTEtzVzZxZVVrdFhLc3FqUTM5dk9aSnY2Q1FqOXVnMGtyeEJyNE5yTHViaGJiS1QvbnlnOW4KNEtWdlpqTEZyZyswZXpkYU0yaVMveGU2ZjBMTXhidEh5RWlpSU9JK2VYeG5mTGQ4VnIrNUxkbXNFbSt0ejl6RQpBNHAvY05IcUxWU0QxeWhzM04vY2hzNDFtUlJjZi9Ubkw3b0w4ZXdvUWNMNUtuRXp0TzJpUlB4V0pINUhZTlJRCmNPRzB0RnR4WCtORHZTcTFNMkJyL2hEbjJ6VzBoSlNxRnZEV2ZVT2RaWDhROSszM05IeXM2NkcrRXM2VVRqMFgKVmI4NmFSdG1NQkhueVJKODQ2Y3lKbDlXYUZhWC9aUno4L05NdTMzUTdTYXBsckdTenJjc2Y5OStBanAyTklyOApBUDd2bHFEYWhHSzZ0akxET0VsUzBkRHZ4MWRUbkFVaEFrU0cyY1ZHTi9HdkpLelRLNUZxdStHUStwWEg4ZkhGClRIWU9uNUJqSGU2bGViSVo4aUQxTGUyaTBWc3FBbjhCcTVtYWx0eE93dTRZNUZYUWxvdE9CTlNBTkFGaVBYZ1gKUHcrY01OVHdJb2MrOFl4RHA0cUlSVjI1V0l5T1pYREtEYXo4ODMxa0xjOHo2bTBnRW81YVhtbGdlclpjTTVYVgp5WG1pMlduZER5ZUxFcUJUSXZkc2JqQWZIZXJMWWdWRmFoaitUanhlMEpvRW1xTTZiUEpKb1NETHZLY0tVZVMrClhZbXp4ZmE3UFYrMElkemdSSXY3QVlkUUl5cVIyK3ZBUG5UOFpCd1YyZDZlK0VTWHQvMVlTL3E1VmdVQ0F3RUEKQVFLQ0FnQVJ0bHNVYWR6QUEyWnJqYVBVVFhmbDRUVEE4VDQxZG1zQjVnL2dub21SRzRRbDRPREg0S3FjRE1hdQptOWU0RGszOTh5elh0MEFSZjl4MnFKNXExTmFrdDN5UkVRUFJ5bXJWUmRCNjVWa2s0S2pWVmVhNjZ3STJFTWtYCjYwT2xTTHF4aW43MHpjamdRalRGWDYwTFVUYTdBNTErTjFVVUFHa0lHWXE1M2tua2N6UVhXVThwbU15Zk1Ea04KUTVvdXgvZmNEc2x1aUllWHZZbTRvcTNoWFZjTm5zczhhMHRDWU1FT3ZhL280NW1qd29tRm1Fd2ZlWkpZdS90RApWSWN4ZGJQTlQxb09RZFlTZktYZjVncnF4Qm1tVGthZy9ZdWMvMUxmck9uYWVpb05JMzVxaCt6aUE5bDI2bWZ1ClRYejVac3p2a0FYSC9RSDBhdS9ycExTUmQwaWhTR0VBZ3hQV0V5cmZjWEZLQTNtc2U2MXZNaDRuY1FsQm44T3EKem1vRWdodm5vbEFUVk9EM21wN3BzeC9LdWZFcVAzWHoxNnBGZk8zNldhNUttYVY2ZFZqamVoZ0hOejhBVStYTword2xOZ1FUM1oxTkRIanBncldqZnZtQnA5OUxVaUdwb0M4T1hjMEUvejFLc3p6T09RZGFWZWE1NVlDZmVPdVFFCmFaZThDbWRVaktqNVVKQmlwRnJEenlORkV1VVhxanFZZXVZWFZCT3VaMDd0UVZHTEZ5N0x6T3UyajJvS241ZjgKNkRlZXprc0FaQzVFZis0blpDQTlSQXgvNExRaUFJL1NoeWtRMUxhc0wzTDgvTERMSHdyZzA5TE11MXhUR01UWApldlR2OEM1R0JGa0FmcnI3d0FiS3l1SlpCNVVLVGtmUkpVanNMdTFkQ2pHc0FvbitGd0tDQVFFQXhwQVNKMGoyCk96N04rUE1TOXhUN2QvSFVTRjBBQ3FDNnllcGF0R2trRzM3MUl6aDIwQ2x0dkxwZUhWQno3cTFONHc1cHhpZlIKaitOcHBDY1I0MDhreEZ3ME9Yd3IrMU1SR01xbUJkUzhEK09SVjkwa2ZVTWVHVjhwTExIREE5OVYwT3g0TDIvYgp4K0JIY3VGRDZLVmJqbW1xR0lFNGc0amg1UkRkUVA5WndjcXVkZHhUOW9ySTJXL1Myc2pxRmUrdTF3VkFnUUlhCmZqY3JaQlJhQVJDM1pZa0ZnTEVTUS9RbFUxbFBSNzdITGpvNHZGYkxLOWptTjlMQnczRGRjbDJrTXZNL2NVTjcKenBVK2J0VkpxWkFqMlR6SVVWcFJlc3NLNDlBdFFTeXVlV1hlUGtVWXJkOGl4OXA3WXpqQXFXYzMzQ0E0R2ZOYwp4ejF0K0REUVRWWlNqd0tDQVFFQTFqdWM3M0xDd3lua245U2I0TGhVT01zMFVmeTZrRHBRSWpXd2F1MkFJVUY1CmRLdG1TUkpjRmlMcDVuY1hYT3VXWU1XMTNSUVV0RTc3cVlndVZiMVNLQ1gwdk4yODRvM0tJVURxRU82VExJejAKd3c5REovZnBRWWNpYTVrU0wrLzVXYjhscndneHRQdS9BaWFsVHFtVlNCaHFVaEpmeXZHNGduT1owVi9HYkdoMQpzY2JNakdUdUFyTGduc1dtUE4zMmJpaTlJcEM5aktBOTJjVDBpWHUwVURNeXZCZ1pHbzRMZFZNdWpnRUtBWVhrCloxRG5oOVVhODkyaVp3Nys1NGJNRGhyamNvK3ZrNXlFeW9RZ1E4dnFCRDFyMFhoS3NSLzJuUXMzYVNSK1Arc0UKT1NuM1A2cEN6aTJQUksvZ3crMWxKaENjbythTUFBd241Ulp5bVlzSUt3S0NBUUVBdmE5K0dCZGtXcDZaeDd2MgpIeUhsUk9VNWhWT0txWng0TkZIMENxcnllbTNqSXAxYksycVlVWlc4T01iVnFXblhvUlB3eWdMWitGb29YaytRCmtCVFlLOWxsYnBFSHR4VFluVlZpR3VucUtrZWNYbEo4L0VqMDVRbjZYSjhJakpkNjlKWWlEamNPdnplcktieTIKMGZXOXJDT1hBY2ZZUkJlc3JOWmFkekE0LzU5dTRGcjF2dTFBQ0RBQ1AwMTJDalNwVXZIS2VET1pPWC9jck1PZwpZNm9qZVJUWHMrUDBiZ1E2OEErK1kreUZmTXpUekdBaHdTWjRiMVdnRXVPc09RZnB4MTZHK2QyYzFYSFBiYlBGCnBmMXpzYUNXUU5sR1EwYmFoVjBuRGo3d0FqcmxmNWtraFYxSGJhSnpBd3VCU1pPNFVrcFpMYmxGcFhReXJNbDkKQkpSMVV3S0NBUUFZN2JMalFnMWJ2R0k0SHZ0TWVPYUQvVkZIUVF0TWdSeVYvbjFhMCt3VzhwRjVmQUJZL0dQdQp4MzFFTGhOdjRwSUxETGFPMVNsYm1kMDY2dmZKVGxCakQ1ZWM2b2h5TEdHYTRQemJuNGRNcGRKTmFGYytMV0RkCkdTWnVNcytrK0YyaGpkYUt1WDlmT2ZRT0FnVTJWQkZrNUVKcTdteHJKeGw3Ukl4ZmlxK0NLZDJZSkRQbEdsRi8KeXVUTVZOOTFNYmJkTnF4YmUxQXpMdXBEanVHTnBmRmphN0c1cFd3MlpOVDhnQU5venNJbFR6azJ0SGxjbXZXWgo3dTVZNDZ2UnNTUEplR09ERHlrMUdmOXh1Vkl2MFdpWHViWDBGL1ZKQ3hrZFNSTFhqMEdKbW9WUlNZclZ3N0FtClliTE1JVk1jT1dHTnZsMGJ6Vlg1STNENC9WVzBmRE1sQW9JQkFGWGtKMG5CenZveDZ5RWg0OTJvWW1OM0JsYW4KL1lPMHY3bC96MnRxd3lyQzFicXUwWnZFS1d1ZjZyVVJZWWxIZ01BR3BwakxTRUFpak1GUDdCWU9QOFEwV0R4VgpqWk1XNWZPdk5FL3lqcS9neE8wNE0yM3ZXTzl6S3dpRjhpZjBjK1ZsckZFbDdRMlk2amFOVzc1VnAveEtyeU14ClkwT1Zhd1Q2UGRwM3ZnRDhEWm84NGNSNnRoOGdWL1JkRmh4TW5aOGlvbExlSEFEWFQ2SFVMdnNobWFuTXd6QVkKYTAzSW9EV1duUlFFMEdmeVdnQ3hDeHVWQityVzJFZWhRUVE1WTdpdjcvakpwbnBsOG5YcU5KMUsrZFhuK1dzZQoveGJlVEVFRDZIcUlCVzJxL0pVQmpCQUErb2xEUWgzZVE2RmZ3SzRybnJoakJXV0lZYVIxcy9WUzg0RT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.36.2
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.36.2
    proxy:
        image: registry.k8s.io/kube-proxy:v1.36.2
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.36.2
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNPZ0F3SUJBZ0lRVzNvdTZoTmlxRWNXQXZHODN2S3M2akFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkyTURnek1UQXpNREl4TWxvWERUTTJNRGd5T0RBek1ESXhNbG93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk14Wi9Gd1VxMnZyCnBRclpkdEo4TXpta0VLeHc2Z1hzUUNNMFR2cXB1WVJja3VLaHJUNmV2dEVrZWNMcS9SeDVDUjJaSERZOExBanAKczJhNmU5QjUwWk9qWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVczJOZEltMDY5Z1ZVCm5sS3JNMEYxT0NRTDFTd3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTy9zcGY1OGt6Ny9lQkRqMzg4bFE1bE0Kb09nQUNMU1B2aUFXa1duWGIrVmhBaUVBd09Vak5RaWxrYm1GMUh2YUt4SnQyTi9RWTByWjNmVXRTSlF1aXBXbwpTVzg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUFyYko0ZFZvY0FvSE41NCt2VXM2SkRBMXFKaWRqbG1iRWNBbUpaUzMrUHVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFekZuOFhCU3JhK3VsQ3RsMjBud3pPYVFRckhEcUJleEFJelJPK3FtNWhGeVM0cUd0UHA2KwowU1I1d3VyOUhIa0pIWmtjTmp3c0NPbXpacnA3MEhuUmt3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
