apiVersion: v1
kind: Secret
metadata:
  name: postgres-dbcreds
  namespace: gen3
type: Opaque
stringData:
  username: gen3db
  password: gen3db-password
  host: gen3-db-cluster-rw.gen3-db.svc.cluster.local
  port: "5432"
  database: postgres
