apiVersion: v2
appVersion: master
dependencies:
- condition: access-backend.enabled
  name: access-backend
  repository: file://../access-backend
  version: 0.1.22
- condition: ambassador.enabled
  name: ambassador
  repository: file://../ambassador
  version: 0.1.39
- condition: arborist.enabled
  name: arborist
  repository: file://../arborist
  version: 0.1.36
- condition: argo-wrapper.enabled
  name: argo-wrapper
  repository: file://../argo-wrapper
  version: 0.1.33
- condition: audit.enabled
  name: audit
  repository: file://../audit
  version: 0.1.46
- condition: aws-es-proxy.enabled
  name: aws-es-proxy
  repository: file://../aws-es-proxy
  version: 0.1.44
- condition: aws-sigv4-proxy.enabled
  name: aws-sigv4-proxy
  repository: file://../aws-sigv4-proxy
  version: 0.1.4
- condition: cedar.enabled
  name: cedar
  repository: file://../cedar
  version: 0.1.28
- condition: cohort-middleware.enabled
  name: cohort-middleware
  repository: file://../cohort-middleware
  version: 0.1.25
- name: common
  repository: file://../common
  version: 0.1.38
- condition: dashboard.enabled
  name: dashboard
  repository: file://../dashboard
  version: 0.1.23
- condition: datareplicate.enabled
  name: datareplicate
  repository: file://../datareplicate
  version: 0.1.23
- condition: data-upload-cron.enabled
  name: data-upload-cron
  repository: file://../data-upload-cron
  version: 0.1.8
- condition: embedding-management-service.enabled
  name: embedding-management-service
  repository: file://../embedding-management-service
  version: 0.1.10
- condition: etl.enabled
  name: etl
  repository: file://../etl
  version: 0.1.24
- condition: frontend-framework.enabled
  name: frontend-framework
  repository: file://../frontend-framework
  version: 0.1.31
- condition: fence.enabled
  name: fence
  repository: file://../fence
  version: 0.1.81
- condition: gen3-workflow.enabled
  name: funnel
  repository: file://../funnel
  version: 0.1.31
- condition: gen3-user-data-library.enabled
  name: gen3-user-data-library
  repository: file://../gen3-user-data-library
  version: 0.1.17
- condition: gen3-workflow.enabled
  name: gen3-workflow
  repository: file://../gen3-workflow
  version: 0.1.28
- condition: guppy.enabled
  name: guppy
  repository: file://../guppy
  version: 0.1.40
- condition: hatchery.enabled
  name: hatchery
  repository: file://../hatchery
  version: 0.1.72
- condition: indexd.enabled
  name: indexd
  repository: file://../indexd
  version: 0.1.49
- condition: manifestservice.enabled
  name: manifestservice
  repository: file://../manifestservice
  version: 0.1.45
- condition: metadata.enabled
  name: metadata
  repository: file://../metadata
  version: 0.1.47
- condition: peregrine.enabled
  name: peregrine
  repository: file://../peregrine
  version: 0.1.44
- condition: portal.enabled
  name: portal
  repository: file://../portal
  version: 0.1.62
- condition: requestor.enabled
  name: requestor
  repository: file://../requestor
  version: 0.1.37
- condition: revproxy.enabled
  name: revproxy
  repository: file://../revproxy
  version: 0.1.68
- condition: sheepdog.enabled
  name: sheepdog
  repository: file://../sheepdog
  version: 0.1.46
- condition: ssjdispatcher.enabled
  name: ssjdispatcher
  repository: file://../ssjdispatcher
  version: 0.1.49
- condition: sower.enabled
  name: sower
  repository: file://../sower
  version: 0.1.48
- condition: wts.enabled
  name: wts
  repository: file://../wts
  version: 0.1.43
- condition: zendesk-wrapper.enabled
  name: zendesk-wrapper
  repository: file://../zendesk-wrapper
  version: 0.1.1
- condition: global.netPolicy.enabled
  name: gen3-network-policies
  repository: file://../gen3-network-policies
  version: 0.1.4
- condition: dicom-server.enabled
  name: dicom-server
  repository: file://../dicom-server
  version: 0.1.33
- condition: ohif-viewer.enabled
  name: ohif-viewer
  repository: file://../ohif-viewer
  version: 0.1.16
- condition: orthanc.enabled
  name: orthanc
  repository: file://../orthanc
  version: 0.1.17
- condition: gen3-analysis.enabled
  name: gen3-analysis
  repository: file://../gen3-analysis
  version: 0.1.14
- condition: ohdsi-atlas.enabled
  name: ohdsi-atlas
  repository: file://../ohdsi-atlas
  version: 0.1.2
- condition: ohdsi-webapi.enabled
  name: ohdsi-webapi
  repository: file://../ohdsi-webapi
  version: 0.1.7
- condition: global.dev
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.10.2
- condition: global.dev
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.9.13
- condition: neuvector.enabled
  name: neuvector
  repository: file://../neuvector
  version: 0.1.2
- condition: jeg.enabled
  name: jeg
  repository: file://../jeg
  version: 0.1.3
- condition: workspace-proxy.enabled
  name: workspace-proxy
  repository: file://../workspace-proxy
  version: 0.1.3
- condition: vectis-overlays.enabled
  name: vectis-overlays
  repository: file://../vectis-overlays
  version: 0.1.3
description: Helm chart to deploy Gen3 Data Commons
maintainers:
- email: ahilt@uchicago.edu
  name: ahilt
- email: ajoa@uchicago.edu
  name: ajoaugustine
- email: emalinowski@uchicago.edu
  name: emalinowski
- email: elisemcastle@uchicago.edu
  name: EliseCastle23
- email: qureshi@uchicago.edu
  name: jawadqur
name: gen3
type: application
version: 0.3.78
