---
- name: Install Kubernetes tools (kubeadm, kubelet, kubectl)
  hosts: no_login
  become: true

  vars:
    k8s_keyring_path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    k8s_repo_url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/
    k8s_version: "1.30.0-1.1"

  tasks:
    # -----------------------------------------------------
    # Ensure keyrings directory exists
    # -----------------------------------------------------
    - name: Create APT keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    # -----------------------------------------------------
    # Download and install Kubernetes GPG key
    # -----------------------------------------------------
    - name: Download Kubernetes release key and dearmor it
      ansible.builtin.shell: |
        curl -fsSL {{ k8s_repo_url }}Release.key | gpg --dearmor -o {{ k8s_keyring_path }}
      args:
        creates: "{{ k8s_keyring_path }}"

    # -----------------------------------------------------
    # Add Kubernetes APT repository
    # -----------------------------------------------------
    - name: Add Kubernetes APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ k8s_keyring_path }}] {{ k8s_repo_url }} /"
        filename: kubernetes
        state: present

    # -----------------------------------------------------
    # Update apt cache
    # -----------------------------------------------------
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true

    # -----------------------------------------------------
    # Install Kubernetes packages
    # -----------------------------------------------------

    - name: Install kubeadm, kubelet, kubectl
      ansible.builtin.apt:
        name:
          - kubelet={{ k8s_version }}
          - kubeadm={{ k8s_version }}
          - kubectl={{ k8s_version }}
        update_cache: yes
        state: present

    # -----------------------------------------------------
    # Hold package versions
    # -----------------------------------------------------
    - name: Hold Kubernetes packages
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    # -----------------------------------------------------
    # Enable and start kubelet service
    # -----------------------------------------------------
    - name: Enable and start kubelet
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
        state: started
