apiVersion: v2
appVersion: master
dependencies:
- name: common
  repository: file://../common
  version: 0.1.38
description: A Helm chart for Kubernetes
name: gen3-workflow
type: application
version: 0.1.28
