apiVersion: v1
kind: ConfigMap
metadata:
  name: gunicorn-conf
data:
  gunicorn.conf.py: |
    wsgi_app = "deployment.wsgi.chart_wsgi:application"
    bind = "0.0.0.0:8000"
    workers = 5
    preload_app = True
    user = "gen3"
    group = "gen3"
    timeout = 300
    keepalive = 2
    keepalive_timeout = 5
  chart_wsgi.py: |
    from indexd.app import get_app
    from indexd.local_settings import settings

    application = get_app(settings)
