externalDatabase:
  host: cnpg-cluster-rw.cnpg-database.svc.cluster.local
  port: 5432
  user: keycloak
  database: keycloak
  password: keycloak-pwd

postgresql:
  enabled: true

image:
  registry: docker.io
  #repository: bitnami/keycloak
  repository: bitnamilegacy/keycloak
  tag: 26.3.3-debian-12-r0
